#!/usr/bin/env node

/**
 * Build script for generating static Next.js pages from landing configs
 * Run with: npm run build:landing
 */

import fs from 'fs';
import path from 'path';

const CONFIGS_DIR = path.join(process.cwd(), 'landing-configs');
const GENERATED_DIR = path.join(process.cwd(), 'src', 'app', 'product');

function getSlugFromFilename(filename: string): string {
  const ext = path.extname(filename);
  return path.basename(filename, ext);
}

function generateDynamicRoutePage(slug: string, config: any): string {
  const configJson = JSON.stringify(config, null, 2);

  return `// Auto-generated static page for slug: ${slug}
// Generated on: ${new Date().toISOString()}
// Edit the config in landing-configs/${slug}.json or .yaml

import { Metadata } from 'next';
import { notFound } from 'next/navigation';

// This file is automatically generated. To customize, edit the config file.
// The dynamic route at src/app/product/[slug]/page.tsx will pick up changes automatically.

const config = ${configJson} as const;

export const metadata: Metadata = {
  title: config.seo?.title || config.name,
  description: config.seo?.description || config.description,
  openGraph: {
    title: config.seo?.title || config.name,
    description: config.seo?.description || config.description,
    images: config.seo?.image ? [config.seo.image] : undefined,
    type: 'website',
  },
};

export default function ${slug.charAt(0).toUpperCase() + slug.slice(1)}Page() {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative py-20 lg:py-32 overflow-hidden bg-gradient-to-br from-blue-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 dark:text-white">
              {config.hero.headline || config.tagline || config.name}
            </h1>
            <p className="mt-6 text-lg sm:text-xl leading-8 text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
              {config.hero.subheadline || config.description}
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <a
                href="${config.hero.ctaUrl}"
                className="rounded-md bg-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-blue-500 transition-colors"
              >
                ${config.hero.ctaText}
              </a>
              <a
                href="#features"
                className="text-sm font-semibold leading-6 text-gray-900 dark:text-white border border-gray-300 dark:border-gray-600 px-6 py-3 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
              >
                Learn More
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
              Why Choose ${config.name}?
            </h2>
          </div>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            ${config.features
              .map(
                (f: any) => `
            <div className="bg-white dark:bg-gray-800 rounded-2xl p-6">
              <div className="text-4xl mb-4">${f.icon}</div>
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">${f.title}</h3>
              <p className="text-gray-600 dark:text-gray-300">${f.description}</p>
            </div>`
              )
              .join('\n')}
          </div>
        </div>
      </section>

      {/* Pricing */}
      ${config.pricing.enabled && config.pricing.plans.length > 0 ? `
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
              Pricing
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-${config.pricing.plans.length} gap-8">
            ${config.pricing.plans
              .map(
                (p: any) => `
            <div class="relative rounded-2xl p-8 ${
                  p.highlighted
                    ? 'bg-blue-600 text-white ring-2 ring-blue-600 ring-offset-2'
                    : 'bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700'
                }">
              ${p.highlighted ? '<div class="absolute -top-4 left-1/2 -translate-x-1/2 bg-blue-500 text-white text-xs font-semibold px-4 py-1 rounded-full">Most Popular</div>' : ''}
              <h3 class="${p.highlighted ? 'text-white' : 'text-gray-900 dark:text-white'} text-xl font-semibold">${p.name}</h3>
              <div class="mt-4 flex items-baseline">
                <span class="${p.highlighted ? 'text-white' : 'text-gray-900 dark:text-white'} text-4xl font-bold">\$${p.price}</span>
                <span class="${p.highlighted ? 'text-blue-100' : 'text-gray-500 dark:text-gray-400'} ml-2">${p.period}</span>
              </div>
              <ul class="mt-6 space-y-4">
                ${p.features
                  .map(
                    (f: string) => `
                <li class="flex items-start">
                  <span class="${p.highlighted ? 'text-blue-200' : 'text-green-500'} flex-shrink-0">✓</span>
                  <span class="${p.highlighted ? 'text-blue-50' : 'text-gray-700 dark:text-gray-300'} ml-3">${f}</span>
                </li>`
                  )
                  .join('\n')}
              </ul>
              <div class="mt-8">
                <a href="${
                  config.pricing.polarEnabled && p.price > 0
                    ? '#polar-checkout'
                    : p.price === 0
                    ? '#get-started'
                    : '#signup'
                }" class="block w-full text-center px-6 py-3 rounded-lg font-semibold transition-colors ${
                  p.highlighted
                    ? 'bg-white text-blue-600 hover:bg-gray-50'
                    : p.price === 0
                    ? 'bg-gray-200 text-gray-900 hover:bg-gray-300'
                    : 'bg-blue-600 text-white hover:bg-blue-500'
                }">
                  ${p.ctaText}
                </a>
              </div>
            </div>
            `
              )
              .join('\n')}
          </div>
        </div>
      </section>
      ` : ''}

      {/* FAQ */}
      ${
        config.faq && config.faq.length > 0
          ? `
      <section className="py-20 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
              Frequently Asked Questions
            </h2>
          </div>
          <div className="space-y-4">
            ${config.faq
              .map(
                (f: any) => `
            <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700">
              <h3 className="p-6 font-semibold text-gray-900 dark:text-white">${f.question}</h3>
              <p className="px-6 pb-6 text-gray-600 dark:text-gray-300">${f.answer}</p>
            </div>
            `
              )
              .join('\n')}
          </div>
        </div>
      </section>
      `
          : ''
      }

      {/* Footer */}
      <footer className="bg-gray-900 dark:bg-black text-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12">
            <div>
              <h3 className="text-2xl font-bold mb-4">${config.name}</h3>
              <p className="text-gray-400 mb-6">${config.footer.tagline}</p>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Product</h4>
              <ul className="space-y-3">
                ${config.footer.links
                  .slice(0, Math.ceil(config.footer.links.length / 2))
                  .map((l: any) => `<li><a href="${l.url}" class="text-gray-400 hover:text-white">${l.label}</a></li>`)
                  .join('\n')}
              </ul>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Company</h4>
              <ul className="space-y-3">
                ${config.footer.links
                  .slice(Math.ceil(config.footer.links.length / 2))
                  .map((l: any) => `<li><a href="${l.url}" class="text-gray-400 hover:text-white">${l.label}</a></li>`)
                  .join('\n')}
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-12 pt-8 text-center text-gray-500 text-sm">
            <p>${
              config.footer.copyright
                .replace('{year}', new Date().getFullYear().toString())
                .replace('{company}', config.name)
            }</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
`;
}

function buildLandingPages() {
  console.log('\n🏗️  Building landing pages from configs...\n');

  if (!fs.existsSync(CONFIGS_DIR)) {
    console.error(`❌ Configs directory not found: ${CONFIGS_DIR}`);
    console.log('Create it with: mkdir landing-configs');
    process.exit(1);
  }

  const files = fs.readdirSync(CONFIGS_DIR).filter((f) => {
    const ext = path.extname(f);
    return ['.json', '.yaml', '.yml'].includes(ext);
  });

  if (files.length === 0) {
    console.log('⚠️  No config files found in landing-configs/');
    return;
  }

  let jsonConfigs = 0;
  let yamlConfigs = 0;

  files.forEach((file) => {
    const ext = path.extname(file);
    const slug = getSlugFromFilename(file);
    const filePath = path.join(CONFIGS_DIR, file);

    try {
      let config: any;

      if (ext === '.json') {
        jsonConfigs++;
        const content = fs.readFileSync(filePath, 'utf-8');
        config = JSON.parse(content);
      } else {
        yamlConfigs++;
        // Only import yaml if needed
        const yaml = require('js-yaml');
        const content = fs.readFileSync(filePath, 'utf-8');
        config = yaml.load(content);
      }

      // Validate with zod-like checks (simplified for build script)
      if (!config.slug || !config.name) {
        console.warn(`⚠️  Skipping ${file}: missing required fields (slug, name)`);
        return;
      }

      // Ensure slug matches filename
      if (config.slug !== slug) {
        console.warn(`⚠️  ${file}: slug "${config.slug}" doesn't match filename. Using "${slug}"`);
      }

      // Create output directory
      const outputDir = path.join(GENERATED_DIR, slug);
      fs.mkdirSync(outputDir, { recursive: true });

      // Generate page
      const pageContent = generateDynamicRoutePage(slug, config);
      fs.writeFileSync(path.join(outputDir, 'page.tsx'), pageContent);

      console.log(`✅ Generated: /product/${slug}`);
    } catch (error: any) {
      console.error(`❌ Error processing ${file}:`, error.message);
    }
  });

  console.log(`\n📊 Summary:`);
  console.log(`   JSON configs: ${jsonConfigs}`);
  console.log(`   YAML configs: ${yamlConfigs}`);
  console.log(`   Total pages generated: ${jsonConfigs + yamlConfigs}`);
  console.log('\n✅ Build complete!\n');
}

// Run build
buildLandingPages();
